spring:
  cloud:
    gateway:
      routes:
        - id: address-service
          uri: lb://ADDRESSAPPLICATION
          predicates:
            - Path=/addresses/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://ORDERAPPLICATION
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://PRODUCTAPPLICATION
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USERAPPLICATION
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1