openapi: 3.0.3

info:
  title: GameOn API
  version: 1.0.0 Beta
  description: GameOn API, implemented with OpenAPI Codegen

paths:
  /users:
    post:
      tags:
        - user, users
      summary: Creates a user
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: User added successfully

    get:
      tags:
        - user, users
      summary: Retrieves all users that a user has access to
      operationId: getAllUsers
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
        '404':
          description: No user was found

  /users/firstName:
    get:
      tags:
        - user, users
      summary: Retrieve user(s) by first name
      operationId: getUsersByFirstName
      parameters:
        - name: firstName
          in: query
          description: first name of users to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found

  /users/lastName:
    get:
      tags:
        - user, users
      summary: Retrieve user(s) by last name
      operationId: getUsersByLastName
      parameters:
        - name: lastName
          in: query
          description: last name of users to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
        '404':
          description: Users not found

  /users/rsaId:
    get:
      tags:
        - user, users
      summary: Retrieve user(s) by rsa id
      operationId: getUsersByRsaId
      parameters:
        - name: rsaId
          in: query
          description: rsa id of users to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/UserDTO'
        '404':
          description: Users not found

  /users/dateOfBirth:
    get:
      tags:
        - user, users
      summary: Retrieve user(s) by last name
      operationId: getUsersByDateOfBirth
      parameters:
        - name: dateOfBirth
          in: query
          description: date of birth of users to retrieve
          required: true
          schema:
            type: date
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
        '404':
          description: Users not found

  /users/addressId:
    get:
      tags:
        - user, users
      summary: Retrieve user(s) by last name
      operationId: getUsersByAddressId
      parameters:
        - name: addressId
          in: query
          description: address id of users to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
        '404':
          description: Users not found

  /users/id:
    get:
      tags:
        - user, users
      summary: Retrieve a user by id
      operationId: getUserById
      parameters:
        - name: id
          in: query
          description: id of a user to retrieve
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found

    delete:
      tags:
        - user, users
      summary: Remove a user by id
      operationId: removeUserById
      parameters:
        - name: id
          in: query
          description: id of a user to remove
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: User removed successfully
        '404':
          description: User not found

    put:
      tags:
        - user, users
      summary: update a user by id
      operationId: updateUserById
      parameters:
        - name: id
          in: query
          description: id of a user to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: User updated successfully
        '404':
          description: User not found

  /users/search:
    get:
      tags:
        - user, users
      summary: Retrieves user by search
      operationId: searchUsers
      parameters:
        - name: id
          in: query
          description: id of a user to search
          required: false
          schema:
            type: string
            format: uuid
        - name: firstName
          in: query
          description: first name of a user to search
          required: false
          schema:
            type: string
        - name: lastName
          in: query
          description: last name of a user to search
          required: false
          schema:
            type: string
        - name: dateOfBirth
          in: query
          description: date of birth of a user to search
          required: false
          schema:
            type: date
        - name: address
          in: query
          description: address of a user to search
          required: false
          schema:
            type: string
        - name: rsaId
          in: query
          description: rsa id of a user to search
          required: false
          schema:
            type: string
      responses:
        '200':
          description: User query successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found

components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          required: false
        firstName:
          type: string
        lastName:
          type: string
        rsaId:
          type: string
        dateOfBirth:
          type: date
          example: "2000-01-01"
        address:
          $ref: '#/components/schemas/AddressDTO'

    AddressDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          required: false
        city:
          type: string
        streetName:
          type: string
        houseNumber:
          type: string
        zipCode:
          type: string